#!/usr/bin/env bash
# Block edits to generated/reference artifacts. Exit 2 => Claude sees stderr as a denial.
set -u
file=$(jq -r '.tool_input.file_path // empty')
[ -z "$file" ] && exit 0

case "$file" in
  */tests/data/*.svg \
  | */locale/*/LC_MESSAGES/*.mo \
  | */po/*.pot \
  | */documentation/src/generators.inc \
  | */inkex/*.inx)
    cat >&2 <<EOF
Blocked: "$file" is a generated artifact, not hand-edited source.

- tests/data/*.svg  -> regenerate with: scripts/boxes <GenName> -o tests/data/<GenName>.svg
  (see the boxes-testing skill for the full workflow; only regenerate after an intentional change.)
- locale/**/*.mo    -> compiled from po/; do not edit.
- po/*.pot          -> regenerate with: scripts/boxes2pot
- inkex/*.inx       -> regenerate with: scripts/boxes2inkscape
- documentation/src/generators.inc -> generated by the docs build.

If you truly need to bypass this, remove or scope the matcher in .claude/settings.json.
EOF
    exit 2
    ;;
esac
exit 0
