#!/usr/bin/env bash
# Block edits to generated/reference artifacts. Exit 2 => Claude sees stderr as a denial.
set -u
file=$(jq -r '.tool_input.file_path // empty')
[ -z "$file" ] && exit 0

case "$file" in
  */tests/data/*.svg \
  | */locale/*/LC_MESSAGES/*.mo \
  | */po/*.pot \
  | */documentation/src/generators.inc \
  | */inkex/*.inx)
    cat >&2 <<EOF
Blocked: "$file" is a generated artifact, not hand-edited source.

- tests/data/*.svg  -> auto-written by tests/test_svg.py on every run. Never edit.
                       If you changed a generator intentionally and need to update its
                       *reference*, copy tests/data/<Name>.svg -> examples/<Name>.svg
                       after the test run (see the boxes-testing skill).
- locale/**/*.mo    -> compiled from po/; do not edit.
- po/*.pot          -> regenerate with: scripts/boxes2pot
- inkex/*.inx       -> regenerate with: scripts/boxes2inkscape
- documentation/src/generators.inc -> generated by the docs build.

If you truly need to bypass this, remove or scope the matcher in .claude/settings.json.
EOF
    exit 2
    ;;
esac
exit 0
